version: '2.4'

services:

  backend:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    command: ash -c "/wait && python app.py"
    environment:
      WAIT_HOSTS: db:3306,redis:6379
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

      FERNET_KEY: 'sIv6jBFwPkNSZP4gVUmzQUnsaMs7g1g7UMRStf5RpCM='
      DATABASE_URL: mysql://socnet:socnetpass@db:3306/socnet
      REDIS_URL: redis://redis:6379

      PORT: 8080
      REST_PORT: 8081

    volumes:
      - ./:/app
    ports:
      - 3001:8080

  db:
     extends:
      file: ../../docker-compose.yml
      service: db

  redis:
     extends:
      file: ../../docker-compose.yml
      service: redis

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
